### ISSUE TITLE
Feature request: Show Warband gold

### ISSUE THREAD

**Issue by keflatbn** [Oppzippy/GoldStockSummary#24]
Hi, 
Thanks for a great quality of life addon for an altoholic :)
Would it be possible to showcase Warband bank gold in this addon?
Since its account gold, I guess will work abit different than guild bank.

**Comment by Oppzippy** [comment]
Thanks for the request, added in v1.6.0. It will show in the total tab.

I can imagine cases where one would want it either excluded or included in the total while using filters, so I took the straight forward approach of putting a checkbox in the total tab for whether or not account bank gold is included in the grand total.

Since the account bank gold does not show in any tables (characters table/realms table), there is currently no export method that includes it.

**Comment by keflatbn** [comment]
Awesome, thank you! Works perfectly!
