### ISSUE TITLE
Guild Bank Money Column

### ISSUE THREAD

**Issue by spaceturttle** [Oppzippy/GoldStockSummary#9]
On live 10.0.7 the Guild Bank Money column appears blank on all characters including when I have interacted with the guild bank. Exporting the data exports no value. I have checked the guilds are not filtered either by the toggle in the options pane or an added filter in the gss interface pane.

**Comment by Oppzippy** [comment]
Is there any chance that you're not running the latest version of Gold Stock Summary (v1.3.7)? I have been unable to reproduce the issue so far, and it sounds similar to #8.

Was the guild bank money working fine right up until the release of 10.0.7?

If you are on the latest version, are any errors reported by [BugSack](https://www.curseforge.com/wow/addons/bugsack)+[BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) when opening the guild bank or the Gold Stock Summary UI?

**Comment by spaceturttle** [comment]
Currently running v1.3.7, no bugs appear, bugsack is empty. I deposited and withdrew gold from the gbank and no change

**Comment by Oppzippy** [comment]
Hm, only thing I can think of then is maybe the characters aren't guild masters? Only guild masters have their guild bank's gold counted, since in most cases, non-gms are not in control of the guild bank's money.

If that's not the issue, I'll probably need to see your `C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT_ID\SavedVariables\GoldStockSummary.lua` file in order to investigate further. If you'd rather not post it publicly since it contains all of your characters, guilds, gold, and filters, you can DM me the file on Discord (Oppzippy#2963).

Another thing you can try if you want, although I would still be left with the question of how the save data got messed up in the first place: log out of wow and try renaming `C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT_ID\SavedVariables\GoldStockSummary.lua` (or wherever you have WoW installed) somewhere else so it doesn't get loaded. If that doesn't fix anything, log out again, delete the new GoldStockSummary.lua, and rename the old one back to restore your settings.

**Comment by spaceturttle** [comment]
Yup. Characters are not GM. Thank you
